import Navbar from "../../components/navbar/navBar"
import Footer from "../../components/footer/Footer"
import AuthProvider from "./context/AuthProvider"
import './global.css';
// import 'react-calendar/dist/Calendar.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <main className='container'>
          <Navbar />
        {children}
        <Footer />
        </main>
        </AuthProvider>
      </body>
    </html>
  )
}
